#pragma once
#include "common/common.h"
string getOSFullName();
BOOL closeWMI();
string getCPUInformation();
int getCPUCount();
int getMemoryCount();
string getMemoryInfo();
int getDiskCount();
string getDiskInfo();
int getVideoDriverCount();
string getVideoDriverInfo();
int getConnectedNetworkDriverCount();
string getConnectedNetworkDriverInfo();